---
title: "Exercise 1. Your turn"
output: html_notebook
---

## Load library packages

```{r message=FALSE, warning=FALSE}
library(janeaustenr)
library(tidyverse)
library(tidytext)
library(wordcloud2)
```


## Your Turn.  Exercise 1.

Goal: Make a basic word cloud for the novel, _Pride and Predjudice_, `pride_prej_novel`

a. Prepare 

```{r}
pride_prej_novel <-  tibble(text = prideprejudice) %>%
  mutate(line = row_number())
```

b. Tokenize `sense_novel` with `unnest_tokens()`

```{r}
pride_prej_novel %>% 
  unnest_tokens(word, text)
```

c. Remove stop-words

```{r}
pride_prej_novel %>% 
  unnest_tokens(word, text) %>% 
  anti_join(get_stopwords())
```

d. calculate word fequency

```{r}
pride_prej_novel %>% 
  unnest_tokens(word, text) %>% 
  anti_join(get_stopwords()) %>% 
  count(word, sort = TRUE) 
```

e. make a simple wordcloud

```{r}
pride_prej_novel %>% 
  unnest_tokens(word, text) %>% 
  anti_join(get_stopwords()) %>% 
  count(word, sort = TRUE) %>% 
  with(wordcloud::wordcloud(word, n, max.words = 100))
```

